### ISSUE TITLE
Cup example error

### ISSUE THREAD

**Issue by AlanBMatthews** [BRL-CAD/brlcad#22]
The cup example given in the tutorial contains an error in so far as the inside and outside heights of the cup are given as 3.5.
However, with a base thickness of 0.25, the inside height should be 3.25

**Comment by brlcad** [comment]
@AlanBMatthews It is intentional.  Notice that the position of the inside cylinder is not [0, 0, 0] but instead nudged up [0, 0, 0.25].  Thus the inside cylinder's height is listed as 3.5 to ensure it extends through the top of the outside cylinder.

The inside height can be any value greater than 3.25, and was kept at 3.5 for simplicity.  Note that you don't want to make the inside cylinder exactly align with the outside cylinder (i.e., height of 3.25) for the reasons explained in the tutorial.  Doing so ensures there's not a thin film remaining where the two surfaces meet.

From a computational geometry standpoint, another reason is that Boolean operations on exactly aligned faces result in undefined behavior and are subject to floating point inaccuracies or differences depending on order of operations.
